# Generated by Django 4.0.6 on 2022-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(),
        ),
    ]
